# -*- coding: utf-8 -*-
"""SemanticSimilarityArabic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/129VOHDCXts0NDDo7qDBE7XDPLSsRM7CR
"""

from abc import ABC, abstractmethod
#the interface of the Package

class SemanticSimilarityArabic(ABC):
    @abstractmethod
    def preprocess(self, sentences):
        pass

    @abstractmethod
    def calculate_similarity_matrix(self, sentences):
        pass

    @abstractmethod
    def find_most_similar_pairs(self, sentences, n):
        pass

    @abstractmethod
    def find_most_similar_sentence(self, sentences, target_sentence):
        pass

    @abstractmethod
    def find_most_similar_pair(self, sentences):
        pass

