# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zees09WfeAngpHEPAUlIMOc_qW_sEb2T
"""

from setuptools import setup, find_packages

setup(
    name='semantic_similarity_arabic',
    version='1.0',
    packages=find_packages(),
    install_requires=[
        # Include any additional dependencies here
        'numpy>=1.18.0',
        'torch>=2.0.1',
        'faiss-cpu>=1.7.4',
        'camel-tools>=1.5.2',
        'transformers>=4.33.1'
    ],
)