name: CI

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different Ubuntu version if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Set up virtual environment
        run: python -m venv semanticsimilarityarabic_v1  # Replace 'myenv' with your desired virtual environment name

      - name: Activate virtual environment
        run: |
          source semanticsimilarityarabic_v1/bin/activate 

      - name: Install required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libboost-all-dev libeigen3-dev
      
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
            
      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt
      
      - name: Install my Python package
        run: pip install .

      - name: Run pytest
        run: pytest test_semantic_similarity/  
